- src/main/java/com/run_us/server/domain/test/TestController.java
- src/main/java/com/run_us/server/global/common/SuccessResponse.java
- src/main/java/com/run_us/server/global/config/WebSocketConfig.java
x
- src/main/java/com/run_us/server/global/config/WebSocketConfig.java : ws 초기 세팅
- src/main/java/com/run_us/server/domain/test/TestController.java : 테스트용 컨트롤러. 소켓 테스트 요청 api 구현
- 테스트 요청 (포스트맨 init test 요청 참고)
1. ws://localhost:8080/ws-hello : 소켓 연결 url (핸드셰이킹)
2. topic/test/hello : 해당 경로 구독
3. app/test/hello : 전송 테스트용 api
- converter 관련 에러 -> SuccessResponse 클래스에 Getter 추가
- 포스트맨 STOMP 테스트 고난
- 마지막에 빈줄 엔터와 NULL문자로 마무리할 것
- url Connect 버튼으로 연결한 후, CONNECT 요청도 전송해줘야 함 
(Connect 버튼 -> CONNECT -> SUBSCRIBE, SEND .... )
-> document 잘 참고하기 . . .
- 정해야 할 것
- 소켓 응답 상태코드 어떻게 줄 지?
- git commit 메세지 태그 중 log가 없어서 그냥 chore로 넣는데 괜찮은지?
- 새 기능 완성 아니고 config 코드나 코드 조금 더한것도 다 feat로 태그 달아야 하는데 괜찮은지? (add 태그 안써도 괜찮을지)
감사합니다~
> [Config/ws init] ws 초기 세팅, 소켓 테스트 요청 api 구현

- src/main/java/com/run_us/server/domain/user/model/User.java
- src/test/java/com/run_us/server/domain/user/model/PenaltyRepositoryTest.java
- src/test/java/com/run_us/server/domain/user/model/UserFixtures.java
- src/test/java/com/run_us/server/domain/user/model/UserRepositoryTest.java
- src/test/java/com/run_us/server/domain/user/model/UserTest.java
#7 
- 빌더가 여러개 선언되어있을 때 생성되는 클래스명이 동일하여 하나가 적용이 안됨.
- 위와 같이 빌더 어노테이션에 이름을 바꾸도록 선언할 수 있으나, **불필요한 생성자의 문제**로 파악하여 생성자를 삭제하는 방향으로 수정.
> [Bug] user entity builder

- .github/workflows/develop-ci.yml
- build.gradle
- src/main/java/com/run_us/server/global/config/RedisConfig.java
- src/test/java/com/run_us/server/config/EmbeddedRedisConfiguration.java
- src/test/java/com/run_us/server/config/TestRedisConfiguration.java
- src/test/java/com/run_us/server/domain/running/RunningRedisRepositoryTest.java
x
- 테스트 환경에서 사용할 Embedded-redis 의존성 추가, 환경 설정
- CI 워크플로우에 application-test.yml 주입 추가
- 레디스 연결 테스트를 위한 `updatePariticpantStatus` 함수의 테스트 코드 작성
- Embedded-Redis를 위한 설정파일과 기존 레디스 환경 설정 분리를 위한 프로필 추가
- 레디스 ConnectionFactory에서 `io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required` 에러가 발생.
제 맥북에는 레디스에 비밀번호가 걸려있어서 환경설정을 안해주니 에러가 생기더라구요. 테스트 환경에서는 개인 환경에 구애받지않고 동작해야하기에 EmbeddedRedis를 추가했습니다.
- Spring Profile은
local / dev / test / prod 4가지 어떨까요?
> [Feature/add embedded redis] 테스트환경을 위한 Embedded Redis 설정

- src/main/java/com/run_us/server/domains/running/controller/StompInterceptor.java
- src/main/java/com/run_us/server/domains/test/TestController.java
- src/main/java/com/run_us/server/domains/user/model/response/UserErrorCode.java
- src/main/java/com/run_us/server/domains/user/model/response/UserException.java
- src/main/java/com/run_us/server/domains/user/service/UserService.java
- src/main/java/com/run_us/server/global/common/GlobalConsts.java
- src/main/java/com/run_us/server/global/config/WebSocketConfig.java
- src/main/java/com/run_us/server/global/exceptions/StompErrorHandler.java
x
- STOMP CONNECT request 시 유저 정보 저장
CONNECT 요청의 헤더 user-id 의 user public key (TSID) 값을 이용해 유저 정보를 조회한 후 session 에 저장합니다.
저장 이후에는 다음과 같이 User 객체를 세션에서 확인할 수 있습니다.
```
User user = accessor.getSessionAttributes().get(SESSION_ATTRIBUTE_USER));
```
- STOMP CONNECT request 시 유저 정보 저장 : 테스트용 요청 구현
해당 로직을 테스트해볼 수 있는 요청을 하나 구현했습니다. 
CONNECT 시 세션에 저장된 사용자 정보를 구독한 경로로 받아볼 수 있습니다.
포스트맨에 테스트 요청 만들어뒀으며 다음과 같은 순서로 테스트 작동 가능합니다.
1. CONNECT : user-id 헤더 추가
2. SUBSCRIBE : /topic/test/user/session
3. SEND : /app/test/user/session
- StompErrorHandler 구현
STOMP 통신 상에서 발생하는 에러 중, 커스텀클래스 BusinessException 로 던지는 예외를 잡아 처리할 수 있도록 했습니다. 
- 인터셉터 등 컨트롤러 밖에서 발생하는 것도 잡아줍니다.
- 에러 발생 시 커스텀 에러코드의 메세지가 클라이언트에게 전달됩니다.
- 그 외 UserErrorCode 와 UserException 만들어서 패키지 여기에 넣었는데 저희 룰과 맞는지 확인 한번 부탁드려요!
x
[질문]
1. 저희 ResponseCode 에서 …
> [Feat/ws auth] STOMP CONNECT 시 User 정보 세션저장, StompErrorHandler 구현

- src/main/java/com/run_us/server/domains/running/controller/StompInterceptor.java
- src/main/java/com/run_us/server/domains/running/controller/SubscriptionService.java
- src/main/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopic.java
- src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
- src/main/java/com/run_us/server/global/common/GlobalConsts.java
- src/test/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopicTest.java
- 기존 코드에서는 subscribe 요청을 존재하지 않는 `destination_path`로 보내도 거절하거나 에러메세지를 반환하지 않았음.
**1. subscribe 시 topic에 따라 검증로직을 추가**
- user-unicast를 위한 `user` (미구현)
- 실시간 달리기 채널을 위한 `runnings` (구현)
**검증로직 추가에 따른 시퀀스 다이어그램**
---
**2. topic을 구분하기 위한 Enum추가**
- 토픽이 추가되면 Enum에 새로 정의합니다.
- 유저가 전송한 `destination_path`를 토큰화하여 토픽을 추출하고 일치하는 토픽이 있으면 처리합니다. 
**부적절한 RunningId를 사용하여 Subscribe요청을 보낸 경우**
---
- 시큐리티에 `path`가 허용되지 않아 로컬환경에서 
```java
.authorizeHttpRequests(authorize -> authorize
.requestMatchers("/runnings/**").permitAll()  // 임시로 추가하고 실행
.requestMatchers("/auth/**").permitAll()
.requestMatchers(GlobalConsts.WS_CONNECT_ENDPOINT).permitAll()
.anyRequest().authenticated()
)
```
임시로 추가하고 진행했습니다.
---
> [Feature/validate subscribe] - 채널 구독시 검증로직 추가

- src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
- src/main/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopic.java
- src/main/java/com/run_us/server/domains/running/exceptions/RunningErrorCode.java
- src/main/java/com/run_us/server/domains/running/service/SubscriptionService.java
- sendToUser 메서드 작성
- aggregate의 경우 예외가 터졌을때 Connection을 끊지않고 재신청하도록 try-catch로 잡아서 메세지 발행
```
try {
runningResultService.saveRunningResult(
requestDto.getRunningId(), requestDto.getUserId(), requestDto.getDataList());
} catch (Exception e) {
sendToUser(sessionId, "/queue/logs", ErrorResponse.of(RunningErrorCode.AGGREGATE_FAILED));
return;
}
``` 
- 정말 어이없지만 헤더에 세션값과 mutable옵션을 주니까 유니캐스트가 작동하는군요.
`StompSubProtocolErrorHandler` 클래스에서 커넥션 맺은 사람한테 단일 메세지 보내는 것을 확인해보니 아래와 같이 코드가 작성되어서
비슷한 로직으로 작성하니 작동했숨돠
```java
@Nullable
public Message<byte[]> handleClientMessageProcessingError(@Nullable Message<byte[]> clientMessage, Throwable ex) {
StompHeaderAccessor accessor = StompHeaderAccessor.create(StompCommand.ERROR);
accessor.setMessage(ex.getMessage());
accessor.setLeaveMutable(true); …
```
> [Fix/send to user] - 특정유저에게 전송하기 수정

- src/main/java/com/run_us/server/domains/running/controller/RunningController.java
- src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
- src/main/java/com/run_us/server/domains/running/controller/model/request/RunningCreateRequest.java
- src/main/java/com/run_us/server/domains/running/controller/model/request/RunningRequest.java
- src/main/java/com/run_us/server/domains/running/controller/model/response/RunningCreateResponse.java
- src/main/java/com/run_us/server/domains/running/domain/LocationData.java
- src/main/java/com/run_us/server/domains/running/domain/RunningType.java
- src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
- src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
- src/main/java/com/run_us/server/domains/running/domain/record/RunningType.java
- src/main/java/com/run_us/server/domains/running/domain/running/ParticipantStatus.java
- src/main/java/com/run_us/server/domains/running/domain/running/Participants.java
- src/main/java/com/run_us/server/domains/running/domain/running/Running.java
- src/main/java/com/run_us/server/domains/running/domain/running/RunningConstraints.java
- src/main/java/com/run_us/server/domains/running/domain/running/RunningDescription.java
- src/main/java/com/run_us/server/domains/running/exception/RunningErrorCode.java
- src/main/java/com/run_us/server/domains/running/repository/PersonalRecordRepository.java
- src/main/java/com/run_us/server/domains/running/repository/RunningRedisRepository.java
- src/main/java/com/run_us/server/domains/running/repository/RunningRepository.java
- src/main/java/com/run_us/server/domains/running/service/RunningLiveService.java
- src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
- src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
- src/main/java/com/run_us/server/domains/running/service/model/PersonalRecordQueryResult.java
- src/main/java/com/run_us/server/domains/running/service/model/RunningAggregation.java
- src/main/java/com/run_us/server/domains/running/service/model/RunningMapper.java
- src/test/java/com/run_us/server/domains/running/PersonalRecordFixtures.java
- src/test/java/com/run_us/server/domains/running/RunningControllerTest.java
- src/test/java/com/run_us/server/domains/running/RunningFixtures.java
- src/test/java/com/run_us/server/domains/running/RunningRedisRepositoryTest.java
- src/test/java/com/run_us/server/domains/running/RunningTest.java
#32
- **달리기 개인 기록 조회 기능 개발**
- 사용자 id와 러닝 id를 이용하여 조회
- **도메인 폴더 디렉토리 재구성**
- `running`, `record` 디렉토리 생성
- `record` 객체들은 id를 통한 간접참조를 하기 때문에 다른 디렉토리에 두어도 문제가 되지않는다고 생각했어요.
- **매퍼 클래스 작성**
- 빌더를 응용서비스계층의 주요 로직에 두는 것보다 매핑하는 클래스를 두어 책임을 분리했어요 
- **테스트 코드 작성**
- 컨트롤러 테스트 작성   
- 서비스의 크기가 계속 커질 것 같아서 여러가지를 시도해봤다가 되돌리고 고민을 했네요..
- 첫번째 시도는 **유즈케이스마다 클래스를 쪼개고** 유즈케이스에서 requestdto를 받아서 매핑 처리를 하고 서비스에게 넘기는 형식이었습니다.
- 표현계층으로부터의 의존(매핑을 포함)을 끊어내고 싶었어요. 
- 너무 클래스가 많아지는 것 같고, 컨트롤러에 많은 유즈케이스 코드가 생성 코드가 생김
- 두번째 시도는 **그냥 DIP를 통한 디커플링**을 하자는 것이었습니다.
- 지금이랑 크게 다른 것은 없고 인터페이스를 추가해서 의존을 끊어내는 방식이었어요.
- 매퍼는 컨트롤러에서 담당하게 했어요. 여기에서 request dto가 도메인의 모델에 의존하게됩니다.
- 셋 그냥 지금처럼 가자!
- 두번째랑 인터페이스 추가안한것만 다른것 같네요
- facade나 usecase가 service레이어라고 치면 컨트롤러는 정말 request를 처리하고 반환만 할 수 있을 것 같아서 여러 시도를 해봤었네요
> [Feature/save running record] - 개인 기록 저장 및 조회 개발

- src/main/java/com/run_us/server/domains/test/TestController.java
- src/main/java/com/run_us/server/global/common/SocketConst.java
- src/main/java/com/run_us/server/global/exception/GlobalSocketExceptionHandler.java
- src/main/java/com/run_us/server/global/exception/SocketBusinessExceptionHandler.java
- src/main/java/com/run_us/server/global/exception/SocketExceptionCustomHandler.java
- src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
x
- `GlobalSocketExceptionHandler` : 소켓 컨트롤러 단 에러 핸들러 구현
- 여기서도 `sendToUser` 기능이 필요한데, 로직이 중복으로 여기저기 생기는 기분이라 특정유저에게 소켓응답해주는 부분을 모듈화하면 어떨까..? 생각해보고 있습니다. 
전에 비슷한 경험으로 다른 프로젝트에서 소켓 응답 전송하는 부분들만 `~SocketResponser` 라는 이름의 클래스로 모아둔 적이 있어요. 꽤 괜찮았어서 `sendToUser` 메서드 빼놓는 것도 나쁘지 않을 것 같다는 생각이 들어요.
- `StompErrorHandler` : intercpetor 단에서 발생하는 에러 핸들링 후 연결 끊기지 않도록 변경
- ERROR 프레임으로 응답되어 연결이 끊김 -> MESSAGE 로 응답되도록 변경
- 에러가 잡혔을 때 어떤 에러인지 판단하는 부분만 기존 핸들러 `StompErrorHandler`에 남기고, 각 에러별 처리 로직을 담을 핸들러 클래스를 별도로 구현하여 분리
- `SocketExceptionCustomHandler` : 처리 로직을 담는 핸들러들의 인터페이스
- `SocketBusinessExceptionHandler` : 처리 로직을 담는 핸들러. `BusinessException` 만을 처리함
지금 저희가 `BusinessException` 을 최상위 커스텀 예외로 사용하고 있어서 일단 그것만 구현했습니다.
추후에 저희 커스텀 예외마다 다른 처리를 해줘야 하는 상황이 오면, 해당 핸들러는 제거하고 대신 이를 참고해 예외 별 처리 핸들러들을 만들어주면 됩니다.
그냥 …
> [Feat/socket handler] 소켓 에러 핸들리 - 기존 핸들러 수정, Controller 단 핸들러 추가 구현

- src/main/java/com/run_us/server/domains/running/controller/RunningController.java
- src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
- src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
- src/main/java/com/run_us/server/domains/running/domain/running/Participants.java
- src/main/java/com/run_us/server/domains/running/domain/running/Running.java
- src/main/java/com/run_us/server/domains/running/repository/PersonalRecordRepository.java
- src/main/java/com/run_us/server/domains/running/service/RunningPreparationService.java
- src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
- src/main/java/com/run_us/server/domains/running/service/model/RunningMapper.java
- src/main/java/com/run_us/server/domains/user/controller/UserController.java
- src/main/java/com/run_us/server/domains/user/domain/OAuthInfo.java
- src/main/java/com/run_us/server/domains/user/domain/Penalty.java
- src/main/java/com/run_us/server/domains/user/domain/Profile.java
- src/main/java/com/run_us/server/domains/user/domain/User.java
- src/main/java/com/run_us/server/domains/user/repository/PenaltyRepository.java
- src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
- src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
- src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
- src/main/java/com/run_us/server/global/common/DateAudit.java
- src/main/java/com/run_us/server/global/common/SuccessResponse.java
- src/test/java/com/run_us/server/domains/running/PersonalRecordFixtures.java
- src/test/java/com/run_us/server/domains/running/RunningControllerTest.java
- src/test/java/com/run_us/server/domains/running/RunningTest.java
- src/test/java/com/run_us/server/domains/user/domain/PenaltyRepositoryTest.java
- src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
- src/test/java/com/run_us/server/domains/user/domain/UserRepositoryTest.java
- src/test/java/com/run_us/server/domains/user/domain/UserTest.java
- ERD에 맞추어 (많은 클래스의) 타입 수정
- id는 모두 Integer
- public_id는 char(13)
- 유저, 프로필 테이블을 가져오기 위해 급히 프로필 분리
- 테스트 코드도 이에 맞게 프로필과 유저 객체 활용하도록 적용
- DateAudit을 상황에 따라 분리(create_at only, 기존 2가지)
- 사실 유저에서 프로필 요소를 바로 쓰고싶었으나 제 JPA 실력이 부족하여 OneToOne을 썼읍니다... 나는 필요하다. 좋은 방법.
- 아마 코드 건든게 많아서 충돌은 많이 날텐데, 타입변환만 잘 맞춰주면 로직상 이슈는 (아마)(거의) 없을겁니다.
> [Refactor/erd-sync] ERD에 맞게 타입 싱크

- src/main/java/com/run_us/server/domains/running/controller/RunningController.java
- src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
- src/main/java/com/run_us/server/domains/running/controller/aop/UserId.java
- src/main/java/com/run_us/server/domains/running/controller/aop/UserIdArgumentResolver.java
- src/main/java/com/run_us/server/domains/running/controller/model/request/RunningRequest.java
- src/main/java/com/run_us/server/domains/running/controller/model/response/RunningResponse.java
- src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
- src/main/java/com/run_us/server/global/config/WebSocketConfig.java
#38 #40 
- **Request DTO에 SPEC 반영 및 불필요한 유저 아이디 필드 삭제**
- **로깅 형식 변경**
```
log.info("action=update_running user_id={} running_id={}", userId, requestDto.getRunningId());
```
- **STOMP 헤더에서 유저 정보를 추출하여 컨트롤러 메소드 파라매터로 주입하는 로직 작성**
- 유저 정보 (user public Id)를 조회하는 로직의 경우 **관심사의 분리**로 처리가능하다고 생각했습니다.
AOP 경험이 적어 여러가지를 시도하다 **Resolver을 통한 주입**으로 해결했습니다. 
[스프링MVC에서의 예시](https://www.baeldung.com/spring-mvc-custom-data-binder)
[웹소켓에서 적용](https://velog.io/@eora21/Spring-Websocket-Websocket-Security-%EB%A7%9B%EA%B9%94%EB%82%98%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0)
그냥 mvc와 비슷하게 WebsocketConfig에서 add해주면됩니다.
- 나중에 로그 처리, 분석에서 **key-value**를 사용하는 것이 좋을 것 같아 로깅 형식을 바꿨습니다 :) 의견남겨주세요
- 이제 User 정보 조회를 위한 복잡한 코드가 사라졌습니다. AOP!
</br>
- 응답 DTO 적용 : 이 부분은 서비스 로직이 변경될 확률이 높아 요구사항을 반영하는 다른 PR에서 …
> [Refactor/running-dto-and-controller] - refactor running controller

- src/main/java/com/run_us/server/domains/running/exception/RunningErrorCode.java
- src/main/java/com/run_us/server/v2/RunningException.java
- src/main/java/com/run_us/server/v2/RunningHttpResponseCode.java
- src/main/java/com/run_us/server/v2/running/run/controller/RunController.java
- src/main/java/com/run_us/server/v2/running/run/controller/RunPreviewController.java
- src/main/java/com/run_us/server/v2/running/run/controller/model/request/SessionRunCreateRequest.java
- src/main/java/com/run_us/server/v2/running/run/domain/Participant.java
- src/main/java/com/run_us/server/v2/running/run/domain/Run.java
- src/main/java/com/run_us/server/v2/running/run/domain/RunPace.java
- src/main/java/com/run_us/server/v2/running/run/domain/RunStatus.java
- src/main/java/com/run_us/server/v2/running/run/domain/RunningPreview.java
- src/main/java/com/run_us/server/v2/running/run/repository/ParticipantRepository.java
- src/main/java/com/run_us/server/v2/running/run/repository/RunRepository.java
- src/main/java/com/run_us/server/v2/running/run/service/DateUtils.java
- src/main/java/com/run_us/server/v2/running/run/service/ParticipantService.java
- src/main/java/com/run_us/server/v2/running/run/service/RunCommandService.java
- src/main/java/com/run_us/server/v2/running/run/service/RunQueryService.java
- src/main/java/com/run_us/server/v2/running/run/service/RunValidator.java
- src/main/java/com/run_us/server/v2/running/run/service/model/GetRunPreviewResponse.java
- src/main/java/com/run_us/server/v2/running/run/service/model/ParticipantInfo.java
- src/main/java/com/run_us/server/v2/running/run/service/model/RunCreateResponse.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCase.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCaseImpl.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunPreviewUseCase.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunPreviewUseCaseImpl.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunRegisterUseCase.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunRegisterUseCaseImpl.java
- src/test/java/com/run_us/server/v2/RunFixtures.java
- src/test/java/com/run_us/server/v2/RunTest.java
v.0.2.0에서 도메인에 대한 큰 변화와 재정립이 이루어지면서 기존의 러닝을 재설계 했습니다.
- Running 도메인 재작성
- Passcode, Live 제외한 기능들 재작성
- Controller - Service - Repository 였던 구조에서 
**Controller - UseCase- Service - Repository**로 작성했습니다.
- Service에 모든 메서드를 담다 보니 너무 커진 책임과 코드가 생겼습니다. 따라서 유즈케이스별로 분리하고 도메인의 서비스를 이용하게 
전환해보았습니다.
#33 에서 그렸던 구조로 결국 가게되었네요. **도메인의 서비스는 Query, Command로 나누어 조회와 수정을 분리**했습니다.
- 며칠간 고민하다가 결국 지금의 코드로 작성을 하게되었어요. 어떻게하면 코드를 이해하기 쉽게짤까를 고민하다가. **영역별로 구분하고
인터페이스만 읽어도 어떤 기능을 담당하겠구나를 알 수 있게 하려다보니 저런 구조가 되었네요.**
- Record 도메인도 작성을 했는데 **구조에 대한 피드백등을 받고 고쳐서 올리기위해** Run도메인만 PR로 올렸습니다.
- Controller > UseCase > Service를 따라가시면 편합니다 ㅎ
> [Feat/update running domain] - 러닝 도메인 재작성

- src/main/java/com/run_us/server/v2/RunningHttpResponseCode.java
- src/main/java/com/run_us/server/v2/running/common/PassCodeGenerator.java
- src/main/java/com/run_us/server/v2/running/common/PassCodeRegistry.java
- src/main/java/com/run_us/server/v2/running/common/RedisPassCodeRegistry.java
- src/main/java/com/run_us/server/v2/running/run/controller/RunController.java
- src/main/java/com/run_us/server/v2/running/run/domain/Run.java
- src/main/java/com/run_us/server/v2/running/run/service/model/CustomRunCreateResponse.java
- src/main/java/com/run_us/server/v2/running/run/service/model/SessionRunCreateResponse.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCase.java
- src/main/java/com/run_us/server/v2/running/run/service/usecase/RunCreateUseCaseImpl.java
- 입장코드 생성 컴포넌트 작성
- 레디스를 통한 단일 키 보장 설계
- 유일 키 생성까지 최대 10번 시도, 10번 초과 시 에러 반환
- 서버 내에서 입장코드 - 런 쌍은 유일해야합니다. (특정 시점)
- live 러닝이 시작되면 입장코드는 다시 반환되며 다른 방에서 획득할 수 있습니다.
- [0-9A-Z]로 생성한 4자리 코드는 36^4 개입니다. 이때 방 생성 요청이 분당 10건, 입장코드가 유지되는 평균시간(러닝이 시작하거나 취소될때까지)을 10분으로 가정하고 입장코드의 충돌확률을 따져보니 0.001% 미만의 확률로 충돌하더군요. (채찍티비에게 시켰습니다.)
트래픽을 높이고 다시 계산해봐도 10번 재시도를 실패할 확률이 매우 낮아 지금의 로직으로 정했습니다.
> [Feat/implement passcode generator for live runningSession] - 입장코드 발급 기능 개발

- src/main/java/com/run_us/server/domains/crew/controller/CrewController.java
- src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewErrorCode.java
- src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewException.java
- src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewHttpResponseCode.java
- src/main/java/com/run_us/server/domains/crew/controller/model/request/CreateJoinRequest.java
- src/main/java/com/run_us/server/domains/crew/controller/model/response/CancelJoinRequestResponse.java
- src/main/java/com/run_us/server/domains/crew/controller/model/response/CreateJoinRequestResponse.java
- src/main/java/com/run_us/server/domains/crew/controller/model/response/CrewJoinRequestInternalResponse.java
- src/main/java/com/run_us/server/domains/crew/domain/Crew.java
- src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
- src/main/java/com/run_us/server/domains/crew/domain/enums/CrewJoinRequestStatus.java
- src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
- src/main/java/com/run_us/server/domains/crew/service/CrewService.java
- src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
- src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCase.java
- src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCaseImpl.java
- src/main/java/com/run_us/server/domains/user/exception/UserException.java
- src/main/java/com/run_us/server/global/config/CacheConfig.java
- src/main/java/com/run_us/server/global/config/WebMvcConfig.java
- src/main/java/com/run_us/server/global/security/annotation/CurrentUser.java
- src/main/java/com/run_us/server/global/security/principal/UserPrincipal.java
- src/main/java/com/run_us/server/global/security/resolver/CurrentUserArgumentResolver.java
- src/main/java/com/run_us/server/global/security/resolver/UserIdResolver.java
JIS-107
> 어딘가 이상한건 아는데, 코드 컨벤션이 크게 바꼈다보니 피드백 받는용으로 초안 빨리 올려봅니다.
> JIS-107은 가입요청과 취소 2가지를 구현해야하는데, 우선 요청까지만 푸시했고, 취소는 피드백 이후 업데이트 예정입니다.
- 현재 로그인한 사용자 정보를 받아오기 위한 `@CurrentUser` 어노테이션 구현
- PublicId와 InternalId만을 가지는 가벼운 객체인 UserPrincipal 생성
- Security의 책임과 User-Auth 강결합 구조 사이에서 타협해서 UserIdResolver에게 예외적인 UserRepository 적용
- 컨트롤러에서 `@CurrentUser UserPrincipal userPrincipal` 형식으로 사용하면 됩니다.
- 크루 가입요청 엔드포인트 구현
- 외부 노출경계인 컨트롤러만 userPublicId 정보 활용 / 내부 로직부터는 userInternalId만 사용
- 이로인해
- 내부용 DTO `CrewJoinRequestInternalResponse` 분리
- useCase가 아닌 컨트롤러가 SuccessResponse 생성
- 상세사유
- UseCase부터는 순수한 비즈니스 로직을 담당하기에 userInternalId가 타당
- userPrincipal 객체는 웹 계층의 구현이기에, ID 변환의 책임은 표현계층인 컨트롤러에게 있음
- 위에도 적어놨지만,, 엔티티 오늘 머지되기 전에 미리 작업하던걸 피드백 용으로 빠르게 업로드한거라 코드가 좀 우당탕탕입니다.
- 아직도 UseCase와 Service의 명확한 구분을 모르겠읍니다,,, …
> [Feat/crew join request process] - 크루 가입요청 생성 및 취소

- src/main/java/com/run_us/server/domains/crew/controller/CrewController.java
- src/main/java/com/run_us/server/domains/crew/controller/model/request/CreateCrewRequest.java
- src/main/java/com/run_us/server/domains/crew/controller/model/response/CreateCrewResponse.java
- src/main/java/com/run_us/server/domains/crew/domain/Crew.java
- src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
- src/main/java/com/run_us/server/domains/crew/domain/CrewMembership.java
- src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
- src/main/java/com/run_us/server/domains/crew/service/CrewCommandService.java
- src/main/java/com/run_us/server/domains/crew/service/usecase/CreateCrewUseCase.java
- src/main/java/com/run_us/server/domains/crew/service/usecase/CreateCrewUseCaseImpl.java
- src/test/java/com/run_us/server/domains/crew/domain/CrewFixtures.java
- src/test/java/com/run_us/server/domains/crew/domain/CrewTest.java
close #<issue_num>
- 크루 생성 api 구현입니다.
- 최근 merge 된 PR 에 현재님이 만들어주신 @CurrentUser 어노테이션이 있었죠.
그거 올라오기 전부터 짜던 코드라 해당 어노테이션을 사용하지 않고 있었고, 사용하는 걸로 변경하려다가 의문이 한가지 들어서
일단 적용하지 않고 올립니다. 질문 결과에 따라 다음 PR에서 수정하겠습니다.
[의문]
1. 지금 @CurrentUser 는 사용자의 public id 로 DB 에서 User 를 조회해 public, internal Id 만 컨트롤러에 전달해주고 있는데요.
id에 해당하는 User 객체가 필요하면 DB를 한번 더 다녀와야 하는 상황입니다.
User 를 통으로 담지 않음으로써 도메인 의존을 줄이는 대신 쿼리를 한번 더 날리는 게 바람직한.. 방향이 맞겠죠?
2. internal id 를 받아왔는데 public id 를 사용할 일이 있을까요? UserPrincipal 에 public id 도 담는 것이 효용성이 있을지 궁금합니다.
감사합니다.
> [feat/create-crew] 크루 생성 api 구현

- src/main/java/com/run_us/server/domains/running/run/controller/RunController.java
- src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionRunCreateRequest.java
- src/main/java/com/run_us/server/domains/running/run/domain/Run.java
- src/main/java/com/run_us/server/domains/running/run/domain/RunningPreview.java
- src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
- src/main/java/com/run_us/server/domains/running/run/service/RunCommandService.java
- src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
- src/main/java/com/run_us/server/domains/running/run/service/model/HostInfo.java
- src/main/java/com/run_us/server/domains/running/run/service/model/JoinedRunPreviewResponse.java
- src/main/java/com/run_us/server/domains/running/run/service/model/RunCreateDto.java
- src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCase.java
- src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
- src/main/java/com/run_us/server/domains/running/run/service/usecase/RunPreviewUseCase.java
- src/main/java/com/run_us/server/domains/running/run/service/usecase/RunPreviewUseCaseImpl.java
- src/test/java/com/run_us/server/domains/running/RunFixtures.java
- src/test/java/com/run_us/server/domains/running/RunRepositoryTest.java
- src/test/java/com/run_us/server/domains/running/RunTest.java
JIS-119 🔥  🚒 
- 참가한 러닝을 조회하는 API 개발
- JPA이슈로 인한 Pace 위치 조정 : 
```
- Running-Preview-Pace
- Running-Pace
```
- ElementCollection이 Embeddable안에 있으면 정말 여러가지 문제가 터지더라구요. 정말 어렵습니다..
- 그래서 Run이 Pace 리스트를 들고있도록 수정했습니다. 좋은방법 or 답 보다는 우선 돌아가게 만들자에 가깝구용
- Preview에서 밖으로 뺐기때문에 기존에 Running을 생성하는 API단이 일부 수정이 불가피했습니다 ㅠ
- RunPace를 들고있는 컨테이너의 위치를 수정했습니다
- 조회하는 API가 두번의 쿼리로 분리됐습니다. RunPace는 ElementCollection인데 조인을 한번에 하려니까 에러가 나더라구요.
DTO 프로젝션을 사용하는데 DTO 프로젝션을 할때는 기본적으로 단일 (flat)데이터로 받아야해요. 그래서 여러 태그가 있을 수 있는 저희 상황에서는 프로젝션으로는 해결이 안됐습니다.
- 요런 조회+Aggregation + ... 등은 기능 구현하고 고민해봐요~
> [Feat/fetch-joined-running] - 참가한 러닝 조회

- src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionAccessLevel.java
- src/main/java/com/run_us/server/domains/running/run/controller/model/request/SessionRunCreateRequest.java
- src/main/java/com/run_us/server/domains/running/run/domain/Run.java
- src/main/java/com/run_us/server/domains/running/run/domain/RunningPreview.java
- src/main/java/com/run_us/server/domains/running/run/domain/SessionAccessLevel.java
- src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
- src/main/java/com/run_us/server/domains/running/run/service/RunCommandService.java
- src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
- src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
- src/main/java/com/run_us/server/domains/running/run/service/model/RunCreateDto.java
- src/main/java/com/run_us/server/domains/running/run/service/usecase/RunCreateUseCaseImpl.java
- src/test/java/com/run_us/server/domains/running/RunFixtures.java
- src/test/java/com/run_us/server/domains/running/RunRepositoryTest.java
- src/test/java/com/run_us/server/domains/running/RunTest.java
JIS-97
- 러닝 생성시 크루ID를 전달하면 크루 세션으로 생성하는 코드 추가
- is/else로 static하게 분기처리
- 크루화면에서 사용할 러닝 조회 함수 작성
- `findByCrewId`
- `findByCrewIdAndAccessLevel` 
- 정기런 여부가 아직 없더라구요 빠른 시일내에 추가하겠습니다.
- 테스트는 db 테스트를 위해 정말 가능한지 확인하는 여부로 작성했습니다.
> [Feat/create-crew-session-run] - 크루용 러닝세션 생성 적용

- src/main/java/com/run_us/server/domains/running/run/repository/RunRepository.java
- src/main/java/com/run_us/server/domains/running/run/service/RunQueryService.java
- src/main/java/com/run_us/server/domains/running/run/service/model/GetRunPreviewResponse.java
#73 
- 카테고리 정보는 별도의 쿼리에서 가져와서 설정하도록 수정.
- jpql말고 native 쿼리 날리고 애플리케이션에서 조립하는 식으로 개선하면 쿼리는 1번으로 끝낼 수 있을 것 같습니당.
> [Fix/fetch-pace-categories] - 페이스 N개를 한번에 조회할때 에러 발생

- src/main/java/com/run_us/server/domains/crew/controller/model/enums/CrewErrorCode.java
- src/main/java/com/run_us/server/domains/crew/domain/Crew.java
- src/main/java/com/run_us/server/domains/crew/domain/CrewJoinRequest.java
- src/main/java/com/run_us/server/domains/crew/domain/CrewMembership.java
- src/main/java/com/run_us/server/domains/crew/repository/CrewJoinRequestRepository.java
- src/main/java/com/run_us/server/domains/crew/repository/CrewRepository.java
- src/main/java/com/run_us/server/domains/crew/service/CrewService.java
- src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
- src/main/java/com/run_us/server/domains/crew/service/usecase/CrewJoinUseCaseImpl.java
- src/test/java/com/run_us/server/domains/crew/domain/CrewFixtures.java
- src/test/java/com/run_us/server/domains/crew/domain/CrewJoinRequestRepositoryTest.java
- src/test/java/com/run_us/server/domains/crew/service/CrewValidatorTest.java
CI-fail 이슈, JPA
- JPA 에러로 실패하던 ci 원인 해결
- `CrewJoinRequest` 는 엔티티로, 다른 엔티티들과는 연관관계를 맺지 않고 id를 통한 간접 참조
- JPQL 에러 해결, 불필요한 쿼리문 제거, Repository 분리
- `CrewValidator` 로직 일부 수정
- 여러번 쿼리 수행을 통해 질의하던 방식에서 `CrewJoinRequest`를 한번만 쿼리하고 객체의 상태로 여러 조건 확인하는 방법으로 수정
- `CrewJoinRequest`가 NotFound인 경우는 Service에서 조회하며 에러 반환
- 쿼리 확인, JPA 테스트를 위한 RepositoryTest 작성
- Validator 로직에 Null들이 많이 보이기도하고 그런데 기능 개발 끝내고 리팩토링할때 생각해봐요~
- 계속 수정되고 조회되다보니 엔티티로 유지하되 연관은 걸지 않았습니다.
- @hughesgoon 작업하고 있다고 하신게 있었던 것 같아 conflict가 조금 걱정되네요 ㅠ
> [Fix/crew-domain] - CrewJoinRequest 수정

- src/main/java/com/run_us/server/domains/running/common/RedisPassCodeRegistry.java
- src/main/java/com/run_us/server/domains/running/common/RunningConst.java
- src/main/java/com/run_us/server/domains/running/common/RunningErrorCode.java
- src/main/java/com/run_us/server/domains/running/live/controller/LiveRunningController.java
- src/main/java/com/run_us/server/domains/running/live/controller/RunningSocketController.java
- src/main/java/com/run_us/server/domains/running/live/controller/model/SubscriptionTopic.java
- src/main/java/com/run_us/server/domains/running/live/repository/RunningRedisRepository.java
- src/main/java/com/run_us/server/domains/running/live/service/RunningLiveService.java
- src/main/java/com/run_us/server/domains/running/live/service/model/LiveRunningCreateResponse.java
- src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCase.java
- src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCaseImpl.java
- src/main/java/com/run_us/server/domains/running/live/service/util/RunningKeyUtil.java
- src/main/java/com/run_us/server/domains/running/run/domain/Run.java
- src/main/java/com/run_us/server/domains/running/run/repository/ParticipantRepository.java
- src/main/java/com/run_us/server/domains/running/run/service/ParticipantService.java
- src/main/java/com/run_us/server/domains/running/run/service/RunValidator.java
- src/test/java/com/run_us/server/domains/crew/domain/CrewJoinRequestRepositoryTest.java
- src/test/java/com/run_us/server/domains/crew/service/CrewValidatorTest.java
- src/test/java/com/run_us/server/domains/running/RunTest.java
- src/test/java/com/run_us/server/domains/running/controller/model/enums/SubscriptionTopicTest.java
- 생성한 세션에 대해 실시간 달리기 방을 만드는 API입니다.
- 요구사항은 다음과 같습니다.
1. 시작시간 10분 전에는 세션글 작성자만 대기방을 열 수 있음.
2. 시작시간 이후 5분까지는 세션글 작성자가 대기방을 열 수 있음.
3. 시작시간 5분 이후부터는 참가자가 아무나 열 수 있음.
4. 시작시간 10분 이후에는 세션이 취소된 상태로 간주하고 아무도 열 수 없음.
- 구현 사항
- validator에 대기방 생성에 대한 검증 로직 추가
- 대기방을 생성한 사람은 id를 저장. >> 추후 통계 작업 시 대기방의 방장의 기록을 사용
- 방장에게 passcode와 run_public_id 반환
- #76 `@CurrentUser` 사용에서 유저 아이디를 받지 못하고 익명유저로 id가 넘어가고 있습니다.
ThreadLocal 한 객체인 Authentication을 jwt filter에서 세팅하는 로직이 없어서 그런 것 같습니다. 
- 노션의 비즈니스 요구사항을 열심히 보고 개발했는데, 혹시 잘못된 로직이 있다면 꼭 피드백 부탁드립니다!
> [Run/open-live-session] - 실시간 대기방 생성 API 개발

- src/main/java/com/run_us/server/domains/running/live/controller/LiveRunningController.java
- src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCase.java
- src/main/java/com/run_us/server/domains/running/live/service/usecase/CreateLiveRunningUseCaseImpl.java
- src/main/java/com/run_us/server/global/config/CacheConfig.java
- run live controller에 `@CurrentUser` 사용하던 부분이 있더라고요..? 이것도 수정해서 올립니다.
> [HOTFIX : fix currentUser ripple effect] - run live controller 핫픽스

- src/main/java/com/run_us/server/domains/user/controller/AuthController.java
- src/main/java/com/run_us/server/domains/user/controller/model/request/AuthRefreshRequest.java
- src/main/java/com/run_us/server/domains/user/controller/model/response/UserHttpResponseCode.java
- src/main/java/com/run_us/server/domains/user/domain/AuthResultType.java
- src/main/java/com/run_us/server/domains/user/exception/UserErrorCode.java
- src/main/java/com/run_us/server/domains/user/service/JwtService.java
- src/main/java/com/run_us/server/domains/user/service/UserAuthService.java
- src/main/java/com/run_us/server/global/common/cache/InMemoryCache.java
- src/main/java/com/run_us/server/global/common/cache/RedisInMemoryCache.java
- src/main/java/com/run_us/server/global/common/cache/SpringInMemoryCache.java
- src/main/java/com/run_us/server/global/config/CacheConfig.java
- src/main/java/com/run_us/server/global/config/RedisConfig.java
- InMemoryCache 인터페이스에 Redis 구현체도 연결했습니다.
- 토큰 리프레시 로직을 추가했습니다.
- 리프레시 토큰 rotation 전략을 적용했습니다. 리프레시 토큰은 **단 한번만** 사용 가능합니다.
- auth 관련 코드는 먼 과거 컨벤션이 상당히 안맞는 영역이더군요.. 다 고치기엔 대작업이라 그냥 과거 방식에 맞춰 기능 이어붙였습니다.
> [Feat/auth refresh] - 토큰 리프레시 로직 구현

- .github/workflows/develop-ci.yml
- src/main/java/com/run_us/server/RunUsApplication.java
- src/main/java/com/run_us/server/domains/crew/domain/Crew.java
- src/main/java/com/run_us/server/domains/running/live/controller/RunningSocketController.java
- src/main/java/com/run_us/server/domains/running/live/repository/RunningRedisRepository.java
- src/main/java/com/run_us/server/domains/running/live/service/RunningLiveService.java
- src/main/java/com/run_us/server/domains/running/live/service/RunningWebsocketService.java
- src/main/java/com/run_us/server/global/config/RedisConfig.java
- src/main/resources/META-INF/scripts/update_location.lua
- src/main/resources/application.yml
- src/test/java/com/run_us/server/RunUsApplicationTests.java
- src/test/java/com/run_us/server/config/TestRedisConfiguration.java
- src/test/java/com/run_us/server/domains/crew/service/CrewValidatorTest.java
#77 
- 서버에서 NOAUTH 문제로 레디스 연결이 안되는 이슈가 발생했습니다. 
- pub-sub으로 모든 메세지를 바로 릴레이하던 로직에서 중앙 스케줄러가 push하는 방식으로 구현 변경
- 위치 업데이트의 원자성 + 레디스 요청 횟수를 줄이기 위해, 2번의 request로 처리하던 로직을 lua스크립트로 변경했습니다.
- 부하테스트 시, 과도한 네트워크 IO로 lettuce가 죽어버리는 문제가 발생했습니다.
- 레디스 직렬화에러가 발생하여 새로운 RedisTemplate 객체를 빈으로 등록했습니다. 다만 RedisTemplate을 런타임에 2개 가지고있는 것이 염려되어 <String,String> 도 일괄적으로 처리할 수 있는지 확인해보고 개선하겠습니다.
> [Fix/redis-connection] 레디스 커넥션 문제 해결
